service: serverless-discord-lfg-bot

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8

functions:
  bot:
    handler: src/bot.main
    events:
      - http:
          method: post
          cors: true
          path: lfg
          private: false
    environment:
      DYNAMODB_TABLE_NAME: lfg-bot-${self:provider.stage}
      DISCORD_PUBLIC_KEY: ${file(./env.json):DISCORD_PUBLIC_KEY}
    layers:
      - arn:aws:lambda:us-east-1:965958012583:layer:salt:1
